CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL,
  verifyOtp VARCHAR(255) DEFAULT '',
  verifyOtpExpireAt BIGINT UNSIGNED DEFAULT 0,
  isAccountVerified TINYINT(1) DEFAULT 0,
  resetOtp VARCHAR(255) DEFAULT '',
  resetOtpExpireAt BIGINT UNSIGNED DEFAULT 0,
  role ENUM('student', 'admin') DEFAULT 'student',
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

